name: AI CI feature

on:
  push:
    branches:
      - feature

jobs:
  ci:
    name: AI CI
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v7
        with:
            fetch-depth: 0
            
      # 2. Ruff 설치 + 린트 검사  
      - name: Ruff install
        uses: astral-sh/ruff-action@v3
        with:
            args: "check"

      
      # 3. Ruff로 포맷 검사
      - name: Run Ruff Formatter Check
        run: ruff format --check .
